services:
  - type: web
    name: connect2edtech
    env: node
    buildCommand: npm install && npm run build -w frontend
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 20
