export const coursesData = {
  webdev: {
    key: 'webdev',
    title: 'Web Development',
    subtitle: 'Creating applications and websites for the internet.',
    description:
      'Complete training in both front-end and back-end web development with modern frameworks and tools.',
    price: 4500,
    image: '/assets/Gemini_Generated_Image_lu6gizlu6gizlu6g.png',
    meta: 'Online • Self-paced',
    features: [
      'Front-End: HTML, CSS, JavaScript frameworks',
      'Back-End: Node.js, Django, ASP.NET',
      'Responsive Design techniques',
      'Database Integration',
      'Web Accessibility standards',
    ],
  },
  datascience: {
    key: 'datascience',
    title: 'Data Science',
    subtitle: 'Extracting insights from data using statistical and ML methods.',
    description:
      'Learn to analyze and interpret complex data with industry-standard tools and techniques.',
    price: 2000,
    image: '/assets/f3ca92ae-1a4e-4d16-8a8e-a9a5b47dd196.jpg',
    meta: 'Online • Self-paced',
    features: [
      'Statistical Analysis',
      'Machine Learning algorithms',
      'Data Visualization with Matplotlib, Seaborn',
      'Big Data Processing with Spark, Hadoop',
      'Hands-on projects with real datasets',
    ],
  },
  security: {
    key: 'security',
    title: 'Cyber Security',
    subtitle: 'Protecting digital systems and data from threats.',
    description:
      'Comprehensive security training covering network security, cryptography, and ethical hacking.',
    price: 2000,
    image: '/assets/Gemini_Generated_Image_sy80b6sy80b6sy80.png',
    meta: 'Online • Self-paced',
    features: [
      'Network Security fundamentals',
      'Cryptography principles',
      'Application Security best practices',
      'Risk Assessment methodologies',
      'Ethical Hacking (CEH, CISSP prep)',
    ],
  },
  technical: {
    key: 'technical',
    title: 'Technical Training',
    subtitle: 'Hands-on training designed to build job-ready technical skills.',
    description:
      'Learn practical concepts through guided modules, real-world exercises, and structured assessments.',
    price: 2000,
    image: '/assets/Gemini_Generated_Image_exv5gwexv5gwexv5.png',
    meta: 'Online • Self-paced',
    features: [
      'Structured learning path',
      'Practical exercises & assignments',
      'Mentor feedback (demo)',
      'Assessments and progress tracking',
      'Career-ready skill focus',
    ],
  },
  management: {
    key: 'management',
    title: 'EdTech Management',
    subtitle: 'End-to-end educational technology implementation and support.',
    description:
      'Get help with LMS setup, digital classroom tooling, student engagement, and academic tech support.',
    price: 4500,
    image: '/assets/Gemini_Generated_Image_lu6gizlu6gizlu6g.png',
    meta: 'Implementation • Support',
    features: [
      'LMS implementation',
      'Digital classrooms setup',
      'Student engagement tooling',
      'Admin dashboards (demo)',
      'Ongoing support & maintenance',
    ],
  },
  skills: {
    key: 'skills',
    title: 'Skill Development Programs',
    subtitle: 'Industry-focused training for practical skills and certifications.',
    description:
      'Build competence with training modules, certification preparation, and real-world learning experiences.',
    price: 4500,
    image: '/assets/Gemini_Generated_Image_sy80b6sy80b6sy80.png',
    meta: 'Blended • Industry aligned',
    features: [
      'Industry-aligned curriculum',
      'Certification preparation',
      'Project-based learning',
      'Interview readiness (demo)',
      'Certificate issuance support',
    ],
  },
  free: {
    key: 'free',
    title: 'Free Training Initiatives',
    subtitle: 'Support for underprivileged learners with mentorship and guidance.',
    description:
      'We provide free digital literacy and guided learning to help create equal opportunities.',
    price: 0,
    image: '/assets/Gemini_Generated_Image_u91l8ru91l8ru91l.png',
    meta: 'Scholarship • Free',
    features: [
      'Digital literacy foundations',
      'Mentorship and guidance',
      'Learning resource access',
      'Community-based support',
      'Outcome tracking (demo)',
    ],
  },
  nontechnical: {
    key: 'nontechnical',
    title: 'Non-Technical Training',
    subtitle: 'Programs focused on communication, analytics, and workplace readiness.',
    description:
      'Improve business and communication foundations with practical modules and guided practice.',
    price: 4500,
    image: '/assets/f3ca92ae-1a4e-4d16-8a8e-a9a5b47dd196.jpg',
    meta: 'Online • Self-paced',
    features: [
      'Business analytics fundamentals',
      'Communication & soft skills training',
      'Interview preparation (demo)',
      'Practical assignments',
      'Progress tracking',
    ],
  },
  emerging: {
    key: 'emerging',
    title: 'Emerging Technologies',
    subtitle: 'Explore IoT, AR/VR, Industry 4.0, and automation concepts.',
    description:
      'Learn emerging technology concepts with hands-on activities and curated learning paths.',
    price: 4500,
    image: '/assets/Gemini_Generated_Image_sy80b6sy80b6sy80.png',
    meta: 'Online • Self-paced',
    features: [
      'IoT fundamentals',
      'AR/VR concepts',
      'Industry 4.0 overview',
      'Automation concepts',
      'Capstone project (demo)',
    ],
  },
  placement: {
    key: 'placement',
    title: 'Career & Placement Support',
    subtitle: 'Career guidance and placement assistance for students.',
    description:
      'Get comprehensive career counseling, interview preparation, and placement assistance to launch your professional career.',
    price: 4500,
    image: '/assets/Gemini_Generated_Image_sy80b6sy80b6sy80.png',
    meta: 'Online • Support',
    features: [
      'Career counseling',
      'Interview preparation',
      'Resume building',
      'Placement assistance',
      'Job market guidance',
    ],
  },
   nontechplus: {
    key: 'nontechplus',
    title: 'Non-Technical Training Plus',
    subtitle: 'Advanced business analytics and management skills.',
    description:
      'Comprehensive non-technical training covering advanced analytics, finance, change management, and more.',
    price: 4500,
    hr: '36hr',
    image: '/assets/f3ca92ae-1a4e-4d16-8a8e-a9a5b47dd196.jpg',
    meta: 'Online • Self-paced',
    features: [
      'Business analytics fundamentals',
      'Financial literacy for managers',
      'Change management frameworks',
      'Risk management & compliance',
      'Customer experience strategy',
    ],
  },
  aptitude: {
    key: 'aptitude',
    title: 'Aptitude Training Program',
    subtitle: 'Quantitative aptitude, logical reasoning, and exam-focused practice.',
    description:
      'Build strong aptitude foundations with timed practice sets, shortcuts, and step-by-step problem-solving techniques.',
    price: 4500,
    hr: '36hr',
    image: '/assets/Gemini_Generated_Image_exv5gwexv5gwexv5.png',
    meta: 'Online • Self-paced',
    features: [
      'Quantitative aptitude fundamentals',
      'Logical reasoning & pattern practice',
      'Time management strategy',
      'Daily practice sets',
      'Mock test preparation',
    ],
  },
  softskills: {
    key: 'softskills',
    title: 'Soft Skills Training Program',
    subtitle: 'Communication, confidence, teamwork, and workplace readiness.',
    description:
      'Develop real-world communication skills with guided activities, role-plays, and practical feedback.',
    price: 4500,
    hr: '36hr',
    image: '/assets/Gemini_Generated_Image_lu6gizlu6gizlu6g.png',
    meta: 'Online • Self-paced',
    features: [
      'Communication & presentation skills',
      'Interview readiness & etiquette',
      'Teamwork & collaboration',
      'Goal setting & self-confidence',
      'Practical speaking exercises',
    ],
  },
  ai1000: {
    key: 'ai1000',
    title: 'Artificial Intelligence Training Program',
    subtitle: 'AI basics to applied ML concepts and hands-on projects.',
    description:
      'Learn AI fundamentals and build practical AI/ML project workflows with curated modules and exercises.',
    price: 4500,
    hr: '36hr',
    image: '/assets/f3ca92ae-1a4e-4d16-8a8e-a9a5b47dd196.jpg',
    meta: 'Online • Self-paced',
    features: [
      'AI & ML fundamentals',
      'Supervised learning basics',
      'Model evaluation & improvements',
      'Hands-on capstone tasks',
      'Project portfolio guidance',
    ],
  },
  mern: {
    key: 'mern',
    title: 'MERN Stack Training Program',
    subtitle: 'Build full-stack web apps with MongoDB, Express, React & Node.',
    description:
      'Learn the MERN stack end-to-end through hands-on web app development and real-world style projects.',
    price: 4500,
    hr: '36hr',
    image: '/assets/Gemini_Generated_Image_lu6gizlu6gizlu6g.png',
    meta: 'Online • Self-paced',
    features: [
      'MongoDB data modelling',
      'Express REST APIs',
      'React front-end development',
      'Node.js backend workflows',
      'Capstone full-stack project',
    ],
  },
  java: {
    key: 'java',
    title: 'Java Training Program',
    subtitle: 'Core Java, OOP concepts, and practical programming for development.',
    description:
      'Strengthen Java fundamentals with OOP concepts, coding practice, and mini-projects.',
    price: 4500,
    hr: '36hr',
    image: '/assets/Gemini_Generated_Image_exv5gwexv5gwexv5.png',
    meta: 'Online • Self-paced',
    features: [
      'Java basics & syntax',
      'Object-Oriented Programming (OOP)',
      'Collections & algorithms practice',
      'Exception handling',
      'Hands-on mini projects',
    ],
  },
  bigdata: {
    key: 'bigdata',
    title: 'Big Data Training Program',
    subtitle: 'Learn big data processing concepts and scalable analytics.',
    description:
      'Understand big data architecture and work on dataset-based analytics workflows.',
    price: 4500,
    hr: '80hr',
    image: '/assets/f3ca92ae-1a4e-4d16-8a8e-a9a5b47dd196.jpg',
    meta: 'Online • Self-paced',
    features: [
      'Big data concepts & architecture',
      'Data processing fundamentals',
      'Analytics pipelines',
      'Practical dataset exercises',
      'Project-based learning',
    ],
  },
  cyber: {
    key: 'cyber',
    title: 'Cyber Security Training Program',
    subtitle: 'Security fundamentals, threat concepts, and ethical hacking basics.',
    description:
      'Learn security essentials with practical modules focused on threats, controls, and ethical hacking concepts.',
    price: 4500,
    hr: '80hr',
    image: '/assets/Gemini_Generated_Image_sy80b6sy80b6sy80.png',
    meta: 'Online • Self-paced',
    features: [
      'Security fundamentals',
      'Threats & vulnerabilities',
      'Network security basics',
      'Ethical hacking concepts',
      'Practical learning tasks',
    ],
  },
  pythonfullstack: {
    key: 'pythonfullstack',
    title: 'Python Full Stack Training Program',
    subtitle: 'Build scalable apps with Python + web development basics.',
    description:
      'Learn Python web development concepts with practical exercises and project-style learning.',
    price: 2000,
    hr: '80hr',
    image: '/assets/Gemini_Generated_Image_exv5gwexv5gwexv5.png',
    meta: 'Online • Self-paced',
    features: [
      'Python programming essentials',
      'Web development fundamentals',
      'Backend logic & APIs',
      'Database integration',
      'End-to-end project modules',
    ],
  },
  cpp2000: {
    key: 'cpp2000',
    title: 'C++ Training Program',
    subtitle: 'Core C++ programming and problem-solving practice.',
    description:
      'Learn C++ fundamentals including OOP, core language constructs, and problem-solving practice.',
    price: 2000,
    hr: '80hr',
    image: '/assets/Gemini_Generated_Image_exv5gwexv5gwexv5.png',
    meta: 'Online • Self-paced',
    features: [
      'C++ fundamentals',
      'OOP in C++',
      'Data structures basics',
      'Coding assignments',
      'Capstone problem set',
    ],
  },
}

export const normalizeCourseKey = (rawKey) => {
  if (!rawKey) return ''
  const k = String(rawKey).trim().toLowerCase()

  const map = {
    webdev: 'webdev',
    'web development': 'webdev',
    datascience: 'datascience',
    'data science': 'datascience',
    security: 'security',
    'cyber security': 'security',
    program: 'technical',
    technical: 'technical',
    'technical training': 'technical',
    management: 'management',
    'edtech management': 'management',
    skills: 'skills',
    'skill development programs': 'skills',
    free: 'free',
    'free training initiatives': 'free',
    nontechnical: 'nontechnical',
    'non-technical training': 'nontechnical',
    emerging: 'emerging',
    'emerging technologies': 'emerging',
    placement: 'placement',
    'career & placement support': 'placement',
    nontechplus: 'nontechplus',
    'non-technical training plus': 'nontechplus',

    aptitude: 'aptitude',
    'aptitude training': 'aptitude',
    'aptitude training program': 'aptitude',

    softskills: 'softskills',
    'soft skills': 'softskills',
    'soft skills training': 'softskills',
    'soft skills training program': 'softskills',

    ai1000: 'ai1000',
    ai: 'ai1000',
    'artificial intelligence': 'ai1000',
    'artificial intelligence training program': 'ai1000',

    mern: 'mern',
    'mern stack': 'mern',
    'mern stack training program': 'mern',

    java: 'java',
    'java training': 'java',
    'java training program': 'java',

    bigdata: 'bigdata',
    'big data': 'bigdata',
    'big data training program': 'bigdata',

    cyber: 'cyber',
    'cyber security training program': 'cyber',

    pythonfullstack: 'pythonfullstack',
    'python full stack': 'pythonfullstack',
    'python full stack training program': 'pythonfullstack',

    cpp2000: 'cpp2000',
    cpp: 'cpp2000',
    cplusplus: 'cpp2000',
    'c++': 'cpp2000',
    'c plus plus': 'cpp2000',
    'c++ training program': 'cpp2000',
  }

  return map[k] || Object.keys(coursesData).find((x) => x.toLowerCase() === k) || k
}
